# Generated by Django 5.1.2 on 2024-10-21 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('learner', 'Learner'), ('tutor', 'Tutor')], default='learner', max_length=10),
        ),
    ]
